#!/bin/bash
TESTS="$@"
if [ -z "$TESTS" ]
then
  TESTS=/submission/test*.js
fi
cd /wdio
node_modules/.bin/mocha -R mocha-spec-json-output-reporter --reporter-options fileName=wdio-0-0-json-reporter.log $TESTS
capture node wdio-render.js
